### ISSUE TITLE
메인페이지 searchBar 수정 및 검색 페이지네이션 스크린 제작

### ISSUE THREAD

**Issue by yooleng** [PRism-Works/PRism-FE#84]
## 📌 ISSUE 종류

- [x] FEAT
- [ ] STYLE
- [ ] REFACTOR
- [ ] CHORE
- [ ] FIX
- [ ] CI
- [ ] MERGE
- [ ] DOCS

<br/>

## 🔎 작업 내용

- [x] 메인페이지 searchBar 수정
- [x] 검색 페이지네이션 스크린 제작

<br/>

**Comment by JANGSEYEONG** [comment]
#88
